### ISSUE TITLE
Including optional proto fields as keyword params in service method signatures

### ISSUE THREAD

**Issue by BenRKarl** [googleapis/gapic-generator-python#487]
Right now optional proto fields are left out of service method signatures, for instance `page_size` [here](https://github.com/googleapis/googleapis/blob/master/google/ads/googleads/v3/services/google_ads_service.proto#L276).

To pass these values we need to initialize the request object, update its fields with the optional and required values, then pass it into the method.

Is there a reason we can't expose optional params as keyword params as well as the required ones? Is the concern that the signatures would grow too large?

**Comment by hkdevandla** [comment]
@software-dov , can you please take a look?

Naive question: does this support exist in the current monolith generator for python client libs?

**Comment by BenRKarl** [comment]
@hkdevandla The signatures from the monolithic generator are a bit different, but they do support this. Proto fields that are required as represented as positional args (thus will error if not passed) and optional proto fields are represented as keyword args with default values of `None`. 

In the microgenerator all parameters are optional keyword params with an added check in the method body that raises if required params are not passed as keyword args.

I think the best solution for the microgenerator would be to represent all proto fields (both required and optional) as keyword params with the in-body check raising errors only for required fields.

**Comment by software-dov** [comment]
Should be fixed by #509

**Comment by BenRKarl** [comment]
@software-dov in our recent regens these optional fields still appear to be missing from method signatures. I will try to send along more details soon, meanwhile is there a unit test that can be added for #509 to ensure the output?

**Comment by BenRKarl** [comment]
Adding @aohren for visibility.

**Comment by software-dov** [comment]
Fix and verified by fragment tests.
