### ISSUE TITLE
Ordering is not consistent for generated init files

### ISSUE THREAD

**Issue by kolea2** [googleapis/gapic-generator-python#805]
We are receiving synthtool PR changes, but it's just a reordering of the classes. They seem to keep flipping back and forth, as I've merged in the opposite ordering previously: https://github.com/googleapis/python-bigtable/pull/237/files

Opposite example: https://github.com/googleapis/python-bigtable/pull/235/files

**Comment by software-dov** [comment]
Should be fixed by #806

**Comment by kolea2** [comment]
@software-dov Thank you!!

**Comment by kolea2** [comment]
Hi @software-dov, we're still seeing this in recent PRs. Example: https://github.com/googleapis/python-bigtable/pull/298. Anything we're missing on our end that I should fix?

**Comment by software-dov** [comment]
I don't think you're missing anything; this issue is just showing areas where we haven't been consistent with ordering elements in the template. It's basically a case of whack-a-mole.
I'll do another pass on the init files to see if there's anywhere that needs sorting added.
