### ISSUE TITLE
Supported dictionaries not reflected in type annotations

### ISSUE THREAD

**Issue by PicardParis** [googleapis/gapic-generator-python#986]
### Issue

Some methods support dictionaries but this is not reflected in the type annotations.

### Example

This working code triggers a `"dict[str, str]" cannot be assigned to type "ClientOptions | None"` warning:
```
import google.cloud.documentai_v1 as documentai

client_options = dict(api_endpoint="eu-documentai.googleapis.com")
client = documentai.DocumentProcessorServiceClient(client_options=client_options)
```

In the client library generated [source code](https://github.com/googleapis/python-documentai/blob/3edf94a98e2aa91af5d0640f2127ed1baa0ff9a7/google/cloud/documentai_v1/services/document_processor_service/client.py#L304), dictionaries are supported:
```
if isinstance(client_options, dict):
    client_options = client_options_lib.from_dict(client_options)
```
but the typing is incomplete:
```
client_options: Optional[client_options_lib.ClientOptions] = None,
```

Note: This is just an example. There are multiple similar occurrences in different client libraries (`if isinstance(xxx, dict)` could be a marker to find them).

**Comment by software-dov** [comment]
Fixed in current generated surfaces.

**Comment by PicardParis** [comment]
Thanks for the fix!

**Comment by PicardParis** [comment]
- I retested the recent `google-cloud-documentai==1.5.0` version and still see the issue:
  ```
  Argument of type "dict[str, str]" cannot be assigned to parameter "client_options" of type "ClientOptions | None" in function 
  "__init__"
    Type "dict[str, str]" cannot be assigned to type "ClientOptions | None"
      "dict[str, str]" is incompatible with "ClientOptions"
  ```
- If you check the [source](https://github.com/googleapis/python-documentai/blob/1b4eff4e0f6ca34bd12fb5cd01343ca74b4f9633/google/cloud/documentai_v1/services/document_processor_service/client.py#L366), `client_options` supports dictionaries yet its declaration does not:
  ```
      def __init__(
          self,
          *,
          credentials: Optional[ga_credentials.Credentials] = None,
          transport: Union[str, DocumentProcessorServiceTransport, None] = None,
          client_options: Optional[client_options_lib.ClientOptions] = None,
          client_info: gapic_v1.client_info.ClientInfo = DEFAULT_CLIENT_INFO,
      ) -> None:
          if isinstance(client_options, dict):
              client_options = client_options_lib.from_dict(client_options)
  ```
- Expected: `client_options: Union[client_options_lib.ClientOptions, dict, None] = None,`
- Is the issue still present (reopen this issue?) or should client libraries be generated differently?
